spring:
  flyway:
    enabled:true
  datasource:
    url: jdbc:h2:./db/database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  main.allow-bean-definition-overriding: true
  cache.jcache.config: classpath:ehcache.xml
  codec.max-in-memory-size: 10MB
app:
  books:
    max: 1000